modLoader="javafml"
loaderVersion="[36,)"
license="Apache License v2"

[[mods]]
modId="magic_orb_mod"
version="0.1"
displayName="Magic Orb Mod"
credits="Thanks for this mod goes to Java, Minecraft and Forge"
authors="Xminer Mod Team"
description='''
A Magic Orb.
'''

[[dependencies.xmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
